inherit_from: .rubocop_todo.yml
Documentation:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/migrate/*'
   - 'test/models/*'
   - 'config/initializers/*'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
   - 'lib/templates/**/*'
   - 'test/controllers/*'
