inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/migrate/*'
   - 'test/models/*'
   - 'config/initializers/*'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
